# Generated by Django 4.2.5 on 2023-09-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name_and_surname', models.CharField(max_length=255, verbose_name='Adi ve soyadi')),
                ('email', models.EmailField(max_length=254, verbose_name='elektron poctu')),
                ('subject', models.CharField(max_length=255, verbose_name='Movzu')),
                ('message', models.TextField(verbose_name='mesaj')),
            ],
            options={
                'verbose_name': 'elaqe saxlamaq isteyen sexs',
                'verbose_name_plural': 'elaqe saxlamaq isteyen sexsler',
                'ordering': ('-created_at',),
            },
        ),
    ]
