# Generated by Django 4.2.5 on 2023-10-05 17:44

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('main_text', models.TextField(verbose_name='Əsas cümlə')),
                ('sub_text', models.TextField(verbose_name='Alt mətin')),
                ('back_image', models.ImageField(help_text='1366x768', upload_to=services.uploader.Uploader.upload_photo_for_home_header, verbose_name='Arxa plan foto')),
                ('round_image', models.ImageField(help_text='612x612', upload_to=services.uploader.Uploader.upload_photo_for_home_header, verbose_name='Fırlanan foto')),
            ],
            options={
                'verbose_name': 'Ana səhifə başliq',
                'verbose_name_plural': 'Ana səhifə başliq',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('location', models.TextField(verbose_name='Ünvan')),
                ('phone_number', models.TextField(verbose_name='Əlaqə nömrəsi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('working_time', models.TextField(verbose_name='İş vaxtları')),
                ('logo', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_for_logo, verbose_name='Saytın loqosu')),
                ('video_url', models.TextField(blank=True, null=True, verbose_name='Video linki')),
            ],
            options={
                'verbose_name': 'Əsas məlumat',
                'verbose_name_plural': 'Əsas məlumatlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('social_media', models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('yt', 'Youtube'), ('tiktok', 'Tiktok'), ('telegram', 'Telegram'), ('linkedin', 'linkedin')], max_length=255, verbose_name='Sosial media')),
                ('link', models.TextField(verbose_name='Sosial media linki')),
            ],
            options={
                'verbose_name': 'Sosial media hesab',
                'verbose_name_plural': 'Sosial media hesabları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Əlaqə nömrəsi')),
            ],
            options={
                'verbose_name': 'Abunə olan şəxs',
                'verbose_name_plural': 'Abunə olan şəxslər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',), 'verbose_name': 'Əlaqə saxlamaq istəyən şəxs', 'verbose_name_plural': 'Əlaqə saxlamaq istəyən şəxslər'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron poçtu'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name_and_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adi və soyadi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mövzu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_name',
            field=models.CharField(max_length=255, verbose_name='Yeməyin adi'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='count_of_guest',
            field=models.IntegerField(verbose_name='Qonaq sayi'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Adi'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateTimeField(verbose_name='Rezerv tarixi və saati'),
        ),
    ]
